services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: QtriveFrontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    depends_on:
      - backend

  ws-server:
    build:
      context: .
      dockerfile: apps/ws-server/Dockerfile
    container_name: QtriveWsServer
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/Qtrive
    command: sh -c "pnpm --filter @repo/db run db:generate && pnpm run dev"
    depends_on:
      db:
        condition: service_healthy

  backend:
    build:
      context: .
      dockerfile: apps/http-server/Dockerfile
    container_name: QtriveBackend
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/Qtrive
    command: sh -c " pnpm --filter @repo/db run db:generate && npx wait-on
      tcp:db:5432 && pnpm --filter @repo/db run db:push && pnpm run dev "
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: Qtrive_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Qtrive
    volumes:
      - Qtrive_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d Qtrive" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: Qtrive_redis
    ports:
      - "6379:6379"
    volumes:
      - Qtrive_redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  Qtrive_data:
  Qtrive_redis_data:
