services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: QtriveFrontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: apps/http-server/Dockerfile
    container_name: QtriveBackend
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/Qtrive
    env_file:
      - ./apps/http-server/.env
    command: sh -c "pnpm --filter @repo/db run db:generate && pnpm --filter @repo/db run db:migrate && pnpm run dev"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: Qtrive_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Qtrive
    volumes:
      - Qtrive_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  Qtrive_data:
